apiVersion: batch/v1
kind: Job
metadata:
  generateName: plugin-install-
spec:
  template:
    spec:
      containers:
      - name: plugin-manager
        image: cbartram/hearthhub-plugin-manager:0.0.1
        imagePullPolicy: IfNotPresent
{{/*        volumeMounts:*/}}
{{/*        - name: plugins-volume*/}}
{{/*          mountPath: /mnt/plugins*/}}
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      restartPolicy: Never
{{/*      volumes:*/}}
{{/*      - name: plugins-volume*/}}
{{/*        persistentVolumeClaim:*/}}
{{/*          claimName: plugins-volume*/}}
