apiVersion: batch/v1
kind: Job
metadata:
  generateName: mod-install-job-
  labels:
    tenant-discord-id: foo
spec:
  template:
    spec:
      containers:
      - name: plugin-manager
        image: cbartram/hearthhub-plugin-manager:0.0.1
        imagePullPolicy: IfNotPresent
        args:
          - "./plugin-manager"
          - "-discord_id"
          - "foo"
          - "-refresh_token"
          - "bar"
          - "-mod_name"
          - "ValheimPlus"
          - "-personal_mod"
          - "false"
        envFrom:
          - configMapRef:
              name: server-resource-config
          - secretRef:
              name: aws-creds
        volumeMounts:
        - name: plugins-volume
          mountPath: /valheim/BepInEx/plugins/
          subPath: plugins
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      restartPolicy: Never
      volumes:
      - name: valheim-pvc
        persistentVolumeClaim:
          claimName: valheim-pvc-discord-id
